### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [AnasOuahidi/DwarseServer#1]
Your parameters.yml file has been compromised and your login/pwd are now visible on this link:
this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

I also recommand you to plug your open source symfony project to sensioInsight...It's free and help you find all security, performance or quality issue on each commit

https://insight.sensiolabs.com/

Hope this will help you :)

**Comment by AnasOuahidi** [comment]
Done.
Thank You

**Comment by ousamabenyounes** [comment]
It is a pleasure to help other symfony developers :).
I must warn you that your password are still available on your git history

https://github.com/AnasOuahidi/DwarseServer/commit/c202c2775201b59d396798d114865b578bead998

hacker always looks for git history to find password and use them.
You have two solution.

Remove the project, and create the same project without any parameter.yml on your project.
Or second solution use the github recommandation:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/
